apiVersion: v1
kind: ServiceAccount
  name: k8sticket-watcher
  namespace: chris-dev

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
  name: k8sticket-role
  namespace: chris-dev
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - deployments
  verbs:
  - get
  - watch
  - list

  ---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
  name: k8sticket-rolebinding
  namespace: chris-dev
  roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8sticket-role
subjects:
- kind: ServiceAccount
  name: k8sticket-watcher
