# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linting:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    name: golangci-lint
    steps:
      - uses: actions/checkout@master
      - uses: actions-contrib/golangci-lint@v1        
        with:
          # golangci-lint docker release tag
          golangci_lint_version: v1.26 # optional, default is v1.23
          args: --timeout 5m
